name: Update HTML

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Clone Repository
    - uses: actions/checkout@v2

    # Creates Python enviroment
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread==3.7.0 python-dotenv==0.10.5

    # Runs python file
    - name: Parse Google Sheets and Update HMTL
      env:
        GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        SHEET_ID: ${{ secrets.SHEET_ID }}
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "Github Action"

        python ".github/workflows/main.py"

        DIFF=$(git diff)
        if [ -n "$DIFF" ];
        then
          git add .
          git commit --message "Update HTML files from Google Sheet update"
          git push origin main
        fi
